import sys as dih; import os as diddy; import random as drakesnake
sex=drakesnake.choice(diddy.listdir("memes"))
import matplotlib.pyplot as penispenis; import matplotlib.image as mpreg
cock = mpreg.imread("memes/"+sex)
anal = penispenis.imshow(cock)
penispenis.xlabel("Take a good look, then close this window and enter your caption in the terminal.")
penispenis.xticks([]); penispenis.yticks([])
penispenis.show()
cum = input("Enter caption: ")
cock = mpreg.imread("memes/"+sex)
anal = penispenis.imshow(cock)
penispenis.xlabel(cum)
penispenis.xticks([]); penispenis.yticks([])
penispenis.show()
penis = input("Do you wish to save this meme? (y/n): ")
if penis.lower() == "y":
    cock = mpreg.imread("memes/"+sex)
    anal = penispenis.imshow(cock)
    penispenis.xlabel(cum)
    penispenis.xticks([]); penispenis.yticks([])
    gyatt = drakesnake.randint(0,10000000000)
    penispenis.savefig(f"saved memes/meme{gyatt}.png")
    dih.exit()