import sys as dih; import os as diddy; import random as drakesnake; import matplotlib.pyplot as ambatron; import matplotlib.image as mpreg
sex=drakesnake.choice(diddy.listdir("memes"))
cock = mpreg.imread("memes/"+sex)
anal = ambatron.imshow(cock); ambatron.xlabel("Take a good look, then close this window and enter your caption in the terminal."); ambatron.xticks([]); ambatron.yticks([]); ambatron.show()
cum = input("Enter caption: ")
cock = mpreg.imread("memes/"+sex)
anal = ambatron.imshow(cock)
ambatron.xlabel(cum); ambatron.xticks([]); ambatron.yticks([]); ambatron.show()
penis = input("Do you wish to save this meme? (y/n): ")
if penis.lower() == "y":
 cock = mpreg.imread("memes/"+sex)
 anal = ambatron.imshow(cock)
 ambatron.xlabel(cum)
 ambatron.xticks([]); ambatron.yticks([])
 gyatt = drakesnake.randint(0,10000000000)
 ambatron.savefig(f"saved memes/meme{gyatt}.png")
 dih.exit()